### ISSUE TITLE
Relicense engine module

### ISSUE THREAD

**Issue by SirRade** [SirRade/shootr#33]
I have exported the engine module as an own crate at https://github.com/SirRade/websocket-server and relicensed it as MIT. By law I am required to ask all contributors of the repo for their consent in this manner.  

To do so, simply reply here with "I wish to relicense the code under the engine module under the MIT license"

- [x] SirRade
- [x] bash

This issue will then be closed after all contributors have consented and the code has been removed from this repo.

**Comment by SirRade** [comment]
I wish to relicense the code under the engine module under the MIT license

**Comment by bash** [comment]
I wish to relicense the code under the engine module under the MIT license
